# Generated by Django 5.1.2 on 2026-04-26 11:07

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Rasm')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Matn')),
            ],
            options={
                'verbose_name': 'Haqida',
                'verbose_name_plural': 'Haqida',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Banner rasmi')),
                ('image1', models.ImageField(upload_to='banners/', verbose_name='Ikkinchi banner rasmi')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannlar',
            },
        ),
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('experience', models.PositiveIntegerField(verbose_name='Tajriba yillari')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('image', models.ImageField(upload_to='barbers/', verbose_name='Rasm')),
                ('age', models.PositiveIntegerField(verbose_name='Yoshi')),
            ],
            options={
                'verbose_name': 'Sartarosh',
                'verbose_name_plural': 'Sartaroshlar',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefon')),
                ('address', models.CharField(max_length=100, verbose_name='Manzil')),
                ('latitude', models.CharField(max_length=100, verbose_name='Kenglik')),
                ('longitude', models.CharField(max_length=700, verbose_name='Uzunlik')),
                ('logo', models.ImageField(upload_to='logo/photos', verbose_name='Logotip')),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': 'Aloqa',
            },
        ),
        migrations.CreateModel(
            name='DopService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Sarlavhani kiriting')),
                ('name', models.CharField(max_length=200, verbose_name='Xizmat nomi')),
                ('description', models.TextField(verbose_name='Tavsifi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Narxi')),
                ('time', models.CharField(max_length=150, verbose_name='Vaqt (soat:dakika)')),
                ('image', models.ImageField(upload_to='services', verbose_name='Xizmat rasmini kiriting')),
            ],
            options={
                'verbose_name': "Qo'shimcha xizmat",
                'verbose_name_plural': "Qo'shimcha Xizmatlar",
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Rasm')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan sana')),
            ],
            options={
                'verbose_name': 'Galereya',
                'verbose_name_plural': 'Galereyalar',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Foydalanuvchi nomi')),
                ('comment', models.TextField(verbose_name='Izoh')),
                ('stars', models.PositiveIntegerField(verbose_name='Yulduzlar soni')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
            },
        ),
        migrations.CreateModel(
            name='Richtext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Maqola')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Sarlavhani kiriting')),
                ('name', models.CharField(max_length=200, verbose_name='Xizmat nomi')),
                ('description', models.TextField(verbose_name='Tavsifi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Narxi')),
                ('time', models.CharField(max_length=150, verbose_name='Vaqt (soat:dakika)')),
                ('image', models.ImageField(upload_to='services', verbose_name='Xizmat rasmini kiriting')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
            },
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sosyal Medya Adı')),
                ('icon', models.ImageField(upload_to='icon/photos', verbose_name='Social media iconini kiriting png holatda')),
                ('link', models.CharField(max_length=200, verbose_name='Akkaunt linkini kiriting')),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoq',
                'verbose_name_plural': 'Ijtimoiy tarmoqlar',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('link', models.CharField(max_length=200, verbose_name='Havola')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(upload_to='header/image', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videolar',
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lunch_start_time', models.TimeField(blank=True, null=True)),
                ('lunch_end_time', models.TimeField(blank=True, null=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber.barber')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Xususiyat nomi')),
                ('service', models.ManyToManyField(related_name='features', to='barber.service', verbose_name='Xizmat')),
            ],
            options={
                'verbose_name': 'Xizmat qoshimchasi',
                'verbose_name_plural': 'Xizmatlar xususiyatlari',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('service_time', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber.barber')),
                ('dopservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barber.dopservice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber.service')),
            ],
        ),
    ]
