# Generated by Django 5.1.2 on 2026-04-27 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Tasdiqlangan'),
        ),
        migrations.AddField(
            model_name='barber',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='barber',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Django foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='dopservice',
            name='barber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dopservices', to='barber.barber', verbose_name='Sartarosh'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='barber.barber', verbose_name='Sartarosh'),
        ),
        migrations.AddField(
            model_name='service',
            name='barber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='barber.barber', verbose_name='Sartarosh'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Birinchi banner rasmi'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Ikkinchi banner rasmi'),
        ),
    ]
