# Generated by Django 5.1.2 on 2026-04-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_barber_is_approved_barber_telegram_id_barber_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AlterField(
            model_name='barber',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='barbers/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsifi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.CharField(default='60 minut', max_length=150, verbose_name='Vaqt (soat:dakika)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.TextField(blank=True, verbose_name='Sarlavhani kiriting'),
        ),
    ]
