# Generated by Django 5.1.2 on 2026-04-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0004_alter_availability_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services', verbose_name='Xizmat rasmini kiriting'),
        ),
        migrations.AlterField(
            model_name='dopservice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsifi'),
        ),
        migrations.AlterField(
            model_name='dopservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services', verbose_name='Xizmat rasmini kiriting'),
        ),
        migrations.AlterField(
            model_name='dopservice',
            name='time',
            field=models.CharField(default='30 minut', max_length=150, verbose_name='Vaqt (soat:dakika)'),
        ),
        migrations.AlterField(
            model_name='dopservice',
            name='title',
            field=models.TextField(blank=True, verbose_name='Sarlavhani kiriting'),
        ),
    ]
