# Generated by Django 5.1.2 on 2026-04-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0003_add_default_availability'),
        ('barber', '0005_service_image_alter_dopservice_description_and_more'),
    ]

    operations = [
    ]
