# Generated by Django 5.1.2 on 2026-04-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0006_merge_20260429_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Rad etish sababi'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20),
        ),
    ]
